//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataShop.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public long CmtID { get; set; }
        public Nullable<long> CusID { get; set; }
        public Nullable<long> ProID { get; set; }
        public string Content { get; set; }
        public string Image { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
    }
}
