//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataShop.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportBillDetail
    {
        public long ImpID { get; set; }
        public Nullable<long> ProID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<long> Price { get; set; }
    
        public virtual ImportBill ImportBill { get; set; }
        public virtual Product Product { get; set; }
    }
}
