//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataShop.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class SubCategory
    {
        public long SubCateID { get; set; }
        [DisplayName("Tên danh m?c con")]
        public Nullable<long> CateID { get; set; }
        [DisplayName("Tên danh m?c cha")]
        public string SubCateName { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
